version: "3.7"

services:
  php:
    build:
      context: .
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
  postgres:
    image: postgres:15.1
    ports:
      - "5429:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'invoices'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    networks:
      - app-network

volumes:
  postgres:
    driver: local

networks:
  app-network:
    driver: bridge
